### ISSUE TITLE
Properly organize logic/networking into respective folders, or combine

### ISSUE THREAD

**Issue by KadinTucker** [Prophets-of-Profit/Galactic-Rush#58]
Change code is currently in logic, but should perhaps be moved to networking?

**Comment by SaurabhTotey** [comment]
I like the current architecture: logic has game rules and networking does the meta managing of the game like sending it to players and managing events/timing. I do understand the need to merge them together and think this is something we all should discuss.

**Comment by EliaGorokhovsky** [comment]
I agree that the game should be conducted from the networking section.
